#!/bin/bash

remove_venv='rm -rf venv'
create_venv='python3 -m venv venv'
activate_venv='. venv/bin/activate'
install_requirements='pip install -r requirements.txt'
install_requirements_dev='pip install -r requirements-dev.txt'

function prompt_and_execute() {
    local command=$1
    read -p "$command? (y/n): " choice
    case "$choice" in 
        y|Y )
            eval $command
            return 0;;
        * )
            return 1;;
    esac
}

if [ -d venv ]; then
    if ! prompt_and_execute "$remove_venv"; then
        return
    fi
fi

echo $create_venv
eval $create_venv

echo $activate_venv
eval $activate_venv

if [ -f "requirements.txt" ]; then
    prompt_and_execute "$install_requirements"
fi

if [ -f "requirements-dev.txt" ]; then
    prompt_and_execute "$install_requirements_dev"
fi
