#!/bin/bash

if [ -d venv ]; then
    read -p "rm -rf venv? (y/n): " choice
    case "$choice" in 
      y|Y ) rm -rf $VENV_DIR;;
      * ) return;;
    esac
fi

echo "python3 -m venv venv"
python3 -m venv venv

. venv/bin/activate

if [ -f "requirements.txt" ]; then
    read -p "pip install -r requirements.txt? (y/n): " choice
    case "$choice" in 
      y|Y ) pip install -r requirements.txt;;
    esac
fi
